-- =============================================================================
-- Oracle Database Script voor "Seven Steps" Applicatie (Versie 3)
-- =============================================================================
-- Dit script zet de basis databasestructuur op voor een applicatie die
-- mensen verbindt om elkaar te helpen met projecten.
--
-- Wijzigingen t.o.v. V2:
-- - 'SEV_' prefix toegevoegd aan alle tabel-, constraint- en triggernamen.
--
-- Aangemaakt op: 2026-01-01
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabel: SEV_CATEGORIES
-- Beschrijving: Centrale lijst van categorieën/onderwerpen.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_CATEGORIES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL UNIQUE
);

COMMENT ON TABLE SEV_CATEGORIES IS 'Centrale lijst van categorieën (bv. Schrijven, Softwareontwikkeling).';
COMMENT ON COLUMN SEV_CATEGORIES.category_name IS 'De unieke naam van de categorie.';


-- -----------------------------------------------------------------------------
-- Tabel: SEV_APP_USERS
-- Beschrijving: Gebruikers van de applicatie.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_APP_USERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email VARCHAR2(255) NOT NULL UNIQUE,
    bio CLOB,
    created_on DATE DEFAULT SYSDATE NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_on DATE,
    updated_by VARCHAR2(255)
);

COMMENT ON TABLE SEV_APP_USERS IS 'Gebruikers van de applicatie.';


-- -----------------------------------------------------------------------------
-- Tabel: SEV_USER_FOLLOWERS
-- Beschrijving: Koppeltabel die bijhoudt welke gebruiker een andere volgt.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_USER_FOLLOWERS (
    user_id NUMBER NOT NULL,          -- De gebruiker die gevolgd wordt
    follower_id NUMBER NOT NULL,      -- De gebruiker die volgt
    created_on DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_sev_user_followers PRIMARY KEY (user_id, follower_id),
    CONSTRAINT fk_sev_uf_user FOREIGN KEY (user_id) REFERENCES SEV_APP_USERS(id) ON DELETE CASCADE,
    CONSTRAINT fk_sev_uf_follower FOREIGN KEY (follower_id) REFERENCES SEV_APP_USERS(id) ON DELETE CASCADE,
    CONSTRAINT chk_sev_not_self_follow CHECK (user_id != follower_id)
);

COMMENT ON TABLE SEV_USER_FOLLOWERS IS 'Legt de volgers-relatie tussen gebruikers vast.';


-- -----------------------------------------------------------------------------
-- Tabel: SEV_PROJECTS
-- Beschrijving: De hoofdentiteit voor een project dat een gebruiker start.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_PROJECTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(30) DEFAULT 'OPEN' NOT NULL
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_on DATE DEFAULT SYSDATE NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_on DATE,
    updated_by VARCHAR2(255),
    CONSTRAINT fk_sev_projects_owner FOREIGN KEY (owner_user_id) REFERENCES SEV_APP_USERS(id) ON DELETE CASCADE
);

COMMENT ON TABLE SEV_PROJECTS IS 'Projecten die door gebruikers zijn aangemaakt.';


-- -----------------------------------------------------------------------------
-- Tabel: SEV_PROJECT_REQUESTS
-- Beschrijving: Specifieke hulpverzoeken binnen een project.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_PROJECT_REQUESTS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(30) DEFAULT 'OPEN' NOT NULL
        CHECK (status IN ('OPEN', 'FILLED', 'CANCELLED')),
    created_on DATE DEFAULT SYSDATE NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_on DATE,
    updated_by VARCHAR2(255),
    CONSTRAINT fk_sev_req_project FOREIGN KEY (project_id) REFERENCES SEV_PROJECTS(id) ON DELETE CASCADE
);

COMMENT ON TABLE SEV_PROJECT_REQUESTS IS 'Specifieke hulpverzoeken binnen een project.';


-- -----------------------------------------------------------------------------
-- Tabel: SEV_PROJECT_REQUEST_CATEGORIES
-- Beschrijving: Koppeltabel tussen verzoeken en categorieën.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_PROJECT_REQUEST_CATEGORIES (
    request_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT pk_sev_req_cat PRIMARY KEY (request_id, category_id),
    CONSTRAINT fk_sev_rc_request FOREIGN KEY (request_id) REFERENCES SEV_PROJECT_REQUESTS(id) ON DELETE CASCADE,
    CONSTRAINT fk_sev_rc_category FOREIGN KEY (category_id) REFERENCES SEV_CATEGORIES(id) ON DELETE CASCADE
);

COMMENT ON TABLE SEV_PROJECT_REQUEST_CATEGORIES IS 'Koppeltabel voor de relevante categorieën per verzoek.';


-- -----------------------------------------------------------------------------
-- Tabel: SEV_REQUEST_RESPONSES
-- Beschrijving: Reacties van gebruikers op een specifiek hulpverzoek.
-- -----------------------------------------------------------------------------
CREATE TABLE SEV_REQUEST_RESPONSES (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id NUMBER NOT NULL,
    responder_user_id NUMBER NOT NULL,
    message CLOB,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_on DATE DEFAULT SYSDATE NOT NULL,
    created_by VARCHAR2(255) NOT NULL,
    updated_on DATE,
    updated_by VARCHAR2(255),
    CONSTRAINT fk_sev_resp_request FOREIGN KEY (request_id) REFERENCES SEV_PROJECT_REQUESTS(id) ON DELETE CASCADE,
    CONSTRAINT fk_sev_resp_responder FOREIGN KEY (responder_user_id) REFERENCES SEV_APP_USERS(id) ON DELETE CASCADE,
    CONSTRAINT uq_sev_response_per_user UNIQUE (request_id, responder_user_id)
);

COMMENT ON TABLE SEV_REQUEST_RESPONSES IS 'Reacties van gebruikers op hulpverzoeken.';


-- =============================================================================
-- Triggers voor Auditing
-- =============================================================================
CREATE OR REPLACE TRIGGER biu_sev_app_users_audit
BEFORE INSERT OR UPDATE ON SEV_APP_USERS
FOR EACH ROW
DECLARE
    v_user VARCHAR2(255);
BEGIN
    v_user := COALESCE(V('APP_USER'), USER);
    IF INSERTING THEN
        :new.created_by := v_user;
    ELSIF UPDATING THEN
        :new.updated_on := SYSDATE;
        :new.updated_by := v_user;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER biu_sev_projects_audit
BEFORE INSERT OR UPDATE ON SEV_PROJECTS
FOR EACH ROW
DECLARE
    v_user VARCHAR2(255);
BEGIN
    v_user := COALESCE(V('APP_USER'), USER);
    IF INSERTING THEN
        :new.created_by := v_user;
    ELSIF UPDATING THEN
        :new.updated_on := SYSDATE;
        :new.updated_by := v_user;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER biu_sev_proj_req_audit
BEFORE INSERT OR UPDATE ON SEV_PROJECT_REQUESTS
FOR EACH ROW
DECLARE
    v_user VARCHAR2(255);
BEGIN
    v_user := COALESCE(V('APP_USER'), USER);
    IF INSERTING THEN
        :new.created_by := v_user;
    ELSIF UPDATING THEN
        :new.updated_on := SYSDATE;
        :new.updated_by := v_user;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER biu_sev_req_resp_audit
BEFORE INSERT OR UPDATE ON SEV_REQUEST_RESPONSES
FOR EACH ROW
DECLARE
    v_user VARCHAR2(255);
BEGIN
    v_user := COALESCE(V('APP_USER'), USER);
    IF INSERTING THEN
        :new.created_by := v_user;
    ELSIF UPDATING THEN
        :new.updated_on := SYSDATE;
        :new.updated_by := v_user;
    END IF;
END;
/

-- =============================================================================
-- Einde van het script
-- =============================================================================